"""Embed the app icon into a C header the Linux game binary compiles in, so
GTKWindow can set the window icon with no external file dependency.

Emits RAW RGBA (not PNG) so the game can build a GdkPixbuf via
gdk_pixbuf_new_from_data() - that needs no gdk-pixbuf loader *module* (a minimal
system may lack the PNG loader), so the icon works anywhere GTK does.

Reads  banjotooie.png  (next to this script) and writes
  ../rexglue-sdk/src/ui/app_icon_data.h

Run after make_icon.py whenever the icon art changes.  Needs: pip install pillow
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "banjotooie.png")
OUT = os.path.abspath(os.path.join(
    HERE, "..", "rexglue-sdk", "src", "ui", "app_icon_data.h"))
SIZE = 128  # window-icon resolution (128x128 RGBA = 64 KB embedded)

img = Image.open(SRC).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
data = img.tobytes()  # RGBA, row-major, SIZE*SIZE*4 bytes

lines = [
    "// Auto-generated by launcher/gen_icon_header.py - do not edit by hand.",
    "// The Banjo-Tooie port's window icon as raw RGBA, embedded so GTKWindow",
    "// can build a GdkPixbuf with gdk_pixbuf_new_from_data (no loader module).",
    "#pragma once",
    "",
    f"static const int kAppIconWidth = {SIZE};",
    f"static const int kAppIconHeight = {SIZE};",
    "static const unsigned char kAppIconRgba[] = {",
]
for i in range(0, len(data), 16):
    lines.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
lines.append("};")
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"wrote {OUT}  ({SIZE}x{SIZE} RGBA, {len(data)} bytes)")
