#!/usr/bin/env bash
echo "=== Vulkan ICDs ==="
ls /usr/share/vulkan/icd.d/ 2>/dev/null || echo "none"
echo "=== vulkan loader present? ==="
ldconfig -p | grep -i libvulkan || echo "no libvulkan in ldconfig"
echo "=== display env ==="
echo "DISPLAY=${DISPLAY:-<unset>}  WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-<unset>}  XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-<unset>}"
echo "=== X11 sockets ==="
ls -la /tmp/.X11-unix/ 2>/dev/null || echo "no X11 sockets"
echo "=== WSLg ==="
ls /mnt/wslg 2>/dev/null | head || echo "no /mnt/wslg"
echo "=== runtime .so ==="
ls -la /mnt/d/Temp/decomp/rexglue-sdk/out/linux-amd64/*.so 2>/dev/null || echo "no .so"
echo "=== does banjotooie find its libs? ==="
ldd /mnt/d/Temp/decomp/banjotooie-recomp/out/build/linux-amd64-debug/banjotooie 2>&1 | grep -iE "not found|rexruntime|vulkan|SDL" || echo "(no missing libs flagged in grep)"
